/**
 * Synthetic GNSS receiver.
 *
 * Four modes covering what an urban vehicle actually experiences: a clean sky,
 * an urban canyon with poor geometry, a tunnel or jammer, and a spoofer.
 */

import type { Rng } from './rng'
import type { TruthSample } from './truth'

export type GnssMode = 'NOMINAL' | 'DEGRADED' | 'DENIED' | 'SPOOFED'

export interface GnssFix {
  t: number
  x: number
  y: number
  hdop: number
  /** 1-sigma horizontal accuracy implied by hdop, m */
  sigma: number
  /** true when this fix was generated by the spoofer, for scoring only */
  spoofed: boolean
}

/** Metres of 1-sigma error per unit of HDOP. */
const SIGMA_PER_HDOP = 2.5

const PROFILE: Record<GnssMode, { hdop: number; period: number } | null> = {
  NOMINAL: { hdop: 1.2, period: 1.0 },
  DEGRADED: { hdop: 6.0, period: 2.0 },
  DENIED: null,
  SPOOFED: { hdop: 1.2, period: 1.0 },
}

/** How far the spoofer drags the reported position, metres. */
const SPOOF_OFFSET = 420
const SPOOF_BEARING = 0.6

export class GnssSim {
  mode: GnssMode = 'NOMINAL'
  private nextFixT = 0
  private rng: Rng

  constructor(rng: Rng) {
    this.rng = rng
  }

  reset(): void {
    this.nextFixT = 0
    this.mode = 'NOMINAL'
  }

  tick(t: number, truth: TruthSample): GnssFix | null {
    const profile = PROFILE[this.mode]
    if (!profile) return null
    if (t < this.nextFixT) return null

    this.nextFixT = t + profile.period

    const sigma = profile.hdop * SIGMA_PER_HDOP
    const spoofed = this.mode === 'SPOOFED'

    const ox = spoofed ? SPOOF_OFFSET * Math.cos(SPOOF_BEARING) : 0
    const oy = spoofed ? SPOOF_OFFSET * Math.sin(SPOOF_BEARING) : 0

    return {
      t,
      x: truth.x + ox + this.rng.gaussian(0, sigma),
      y: truth.y + oy + this.rng.gaussian(0, sigma),
      hdop: profile.hdop,
      sigma,
      spoofed,
    }
  }
}
