/**
 * Ground truth trajectory.
 *
 * The speed profile is generated by a three-pass method rather than scripted by
 * hand, so the vehicle brakes *before* corners and the stop line the way a real
 * one does. That matters: a profile that decelerates late produces lateral
 * accelerations no car could survive, and the IMU synthesis would then be
 * feeding the estimators physically impossible data.
 */

import { ROUTE_LENGTH, INTERSECTION_S, poseAt, curvatureAt, segmentAt } from './road'

export interface TruthSample {
  t: number
  /** arc length along the route, metres */
  s: number
  x: number
  y: number
  psi: number
  v: number
  omega: number
  aLong: number
}

export interface Truth {
  samples: TruthSample[]
  duration: number
  length: number
}

/** Comfortable lateral acceleration, m/s^2. Sets cornering speed with radius. */
const A_LAT_MAX = 2.2
/** Longitudinal acceleration limit — gives 0 to 14 m/s in roughly 8 s. */
const A_ACCEL = 1.75
/** Braking limit. Higher than accel, as in a real vehicle. */
const A_DECEL = 2.5
/** Dwell at the 4-way stop. This is what makes ZUPT demonstrable. */
const STOP_DURATION = 4.0
/** Station spacing for the speed profile, metres. */
const DS = 1

/**
 * Pass 1 — ceiling: the fastest this vehicle may legally and physically go at
 * each station, given the posted limit and the corner radius.
 */
function speedCeiling(): number[] {
  const n = Math.floor(ROUTE_LENGTH / DS) + 1
  const ceiling = new Array<number>(n)
  for (let i = 0; i < n; i++) {
    const s = i * DS
    const k = Math.abs(curvatureAt(s))
    const corner = k > 1e-6 ? Math.sqrt(A_LAT_MAX / k) : Infinity
    ceiling[i] = Math.min(segmentAt(s).speedLimit, corner)
  }
  // Hard zero in a 1 m window at the stop line.
  const stopIdx = Math.round(INTERSECTION_S / DS)
  if (stopIdx >= 0 && stopIdx < n) ceiling[stopIdx] = 0
  return ceiling
}

export function generateTruth(dt: number): Truth {
  const n = Math.floor(ROUTE_LENGTH / DS) + 1
  const v = speedCeiling()

  // Pass 2 — forward: cannot accelerate harder than A_ACCEL.
  v[0] = 0
  for (let i = 1; i < n; i++) {
    v[i] = Math.min(v[i], Math.sqrt(v[i - 1] * v[i - 1] + 2 * A_ACCEL * DS))
  }

  // Pass 3 — backward: must already be slow enough to brake for what is ahead.
  for (let i = n - 2; i >= 0; i--) {
    v[i] = Math.min(v[i], Math.sqrt(v[i + 1] * v[i + 1] + 2 * A_DECEL * DS))
  }

  /*
   * Integrate in the station domain, not the time domain.
   *
   * Time-stepping `s += v*dt` cannot leave a standing start, because v(0) is
   * legitimately zero. Accumulating `dt = ds / v_avg` per station has no such
   * degeneracy: the first metre simply takes a long time, which is correct.
   */
  const stopIdx = Math.round(INTERSECTION_S / DS)
  const tAt = new Array<number>(n)
  tAt[0] = 0
  for (let i = 1; i < n; i++) {
    const vAvg = (v[i - 1] + v[i]) / 2
    tAt[i] = tAt[i - 1] + DS / Math.max(vAvg, 1e-6)
    // The 4 s dwell lands entirely at the stop station.
    if (i === stopIdx) tAt[i] += STOP_DURATION
  }

  /*
   * tAt[stopIdx] is the *departure* time from the stop line, because the dwell
   * was folded into the cumulative sum there. The hold therefore occupies the
   * window ending at that value.
   */
  const dwellEnd = tAt[stopIdx]
  const dwellStart = dwellEnd - STOP_DURATION

  const duration = tAt[n - 1]
  const samples: TruthSample[] = []

  // Resample the station-domain profile onto the uniform dt grid the rest of
  // the simulator runs on.
  let station = 0
  let vPrev = 0
  const steps = Math.floor(duration / dt)

  for (let k = 0; k <= steps; k++) {
    const t = k * dt
    while (station < n - 1 && tAt[station + 1] <= t) station++

    let s: number
    let vNow: number

    const tSpan = tAt[station + 1] - tAt[station]
    const f = tSpan > 1e-9 ? (t - tAt[station]) / tSpan : 0

    if (t >= dwellStart && t < dwellEnd) {
      // Held at the stop line. This is what makes ZUPT demonstrable.
      s = stopIdx * DS
      vNow = 0
    } else {
      s = Math.min(ROUTE_LENGTH, (station + Math.max(0, Math.min(1, f))) * DS)
      vNow = v[station] + (v[Math.min(station + 1, n - 1)] - v[station]) * Math.max(0, Math.min(1, f))
    }

    const p = poseAt(s)
    samples.push({
      t,
      s,
      x: p.x,
      y: p.y,
      psi: p.psi,
      v: vNow,
      omega: vNow * curvatureAt(s),
      aLong: (vNow - vPrev) / dt,
    })
    vPrev = vNow
  }

  return { samples, duration: samples[samples.length - 1].t, length: ROUTE_LENGTH }
}

export function truthAt(truth: Truth, t: number): TruthSample {
  const i = Math.max(0, Math.min(truth.samples.length - 1, Math.round(t / 0.01)))
  return truth.samples[i]
}
